### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by blacksythe** [CJ-MC-Mods/ForgeToBukkitPermissions#1]
Hi downloaded for 1.12.2 sevtech.

Can you please add some documentation how this works and how to apply it to your server.

e.g. The gamestages mod
gamestage add "stage"

And 

Using luckperms for example what would i need to add for this?

Or how do I retrieve this information from the server.

Right now I'm gonna try gamestage.* and hope for the best

**Comment by cjm721** [comment]
> This mod will proxy all of Forge's PermissionsAPI calls to Bukkit's permission API.

It is up to mods to use the Forge Permission API for them to have nodes. Also up to the permissions API  you are using for debugging (or contact the mod developer you want the nodes for).

Of which luckperms already has a page on that: https://github.com/lucko/LuckPerms/wiki/Verbose
